name: Build Flutter Windows Application

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.5' # 根据你的pubspec.yaml中的Flutter版本要求修改

    - name: Install dependencies
      run: flutter pub get

    - name: Build Windows
      run: flutter build windows

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: windows-build
        path: build/windows/runner/Release
